# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hardhat test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compile contracts and run hardhat tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Launch Hardhat tests
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create env file
      run: |
        touch .env
        echo RINKEBY_URL=${RINKEBY_URL} >> .env
        echo MAINNET_URL=${MAINNET_URL} >> .env
        echo MNEMONIC=${MNEMONIC} >> .env
        echo REPORT_GAS=${REPORT_GAS} >> .env
        echo ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY} >> .env
        cat .env
      env: 
        RINKEBY_URL: ${{ secrets.RINKEBY_URL }} 
        MAINNET_URL: ${{ secrets.MAINNET_URL }}
        MNEMONIC: ${{ secrets.MNEMONIC }} 
        REPORT_GAS: ${{ secrets.REPORT_GAS }} 
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }} 
    - run: npx hardhat compile
    - run: npm test
